@baseURL = http://localhost:8080/

@rdpVersion = v1

@username = {{dotenv RDP_USERNAME}}
@password = {{dotenv RDP_PASSWORD}}

@client_id = {{dotenv RDP_CLIENT_ID}}

GET {{{baseURL}}} HTTP/1.1
Content-Type: text/html